### ISSUE TITLE
linshare trying to connect to localhost mongodb while it is configured as external ip

### ISSUE THREAD

**Issue by lacrimal** [linagora/linshare#217]
Found this in logs when starting tomcat with linshare. Don't know it is cluster creation problem or configuration.
On first start all of addresses in linshare.properties was set to 192.168.8.12 so it was not localhost.

`
[INFO]:main:20220310.125257:org.mongodb.driver.cluster:info:**Cluster created with settings {hosts=[localhost:27017]**, mode=MULTIPLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=32}
[INFO]:main:20220310.125257:org.mongodb.driver.cluster:info:Adding discovered server localhost:27017 to client view of cluster
[INFO]:cluster-ClusterId{value='6229e699964cac55140af295', description='null'}-localhost:27017:20220310.125257:org.mongodb.driver.cluster:info:Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70)
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64)
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79)
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)
        ... 3 more

`

**Comment by fmartin-linagora** [comment]
yes I saw that recently too. but it seems there is no impact because the connection is working properly. weird. we need to investigate but it is not important. do not worry.

**Comment by lacrimal** [comment]
This is weird to - have CLI with tomcat and httpd installed on one server and databases on second one.
linshareadmcli tries to open connection with mongo using localhost:27017 while it is remote - is it connected with above?
Thought CLI can be placed on any machine.

`linshareadmcli mail_attachments 946b190d-4c95-485f-bfe6-d288a2de1edd create --cid logo.linshare@linshare.org --name mailAttachment --description 'white logo' /var/www/linshare-ui-user/images/linshare-logo-white.svg

22:11:27 ERROR   : {"message":"Unexpected exception : class com.mongodb.MongoTimeoutException : Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]","errCode":20000} : logo.linshare@linshare.org`

**Comment by tanandy** [comment]
@fmartin-linagora could it be link to smallfiles db or something related (subsidiary db and cnx string)

**Comment by fmartin-linagora** [comment]
So you probably have a bad configuration and LinShare can not store mail attachments neither thumbnails. So it is definitely related to smallfiles database. See [here](https://github.com/linagora/linshare-core/blob/8fc288becdf58567ca2f490356d9e1579fae4a96/src/main/resources/linshare.properties.sample#L141) for latest versions.

**Comment by lacrimal** [comment]
Is smallfiles database mandatory ?
How can detect in real life usage that I'm lacking something in terms of smallfiles database ?
I'm also not using thumbnails as separate engine - is it a problem ?

**Comment by fmartin-linagora** [comment]
Yes, it is mandatory. it is used for storing thumbnails and mail_attachments. So if you do not use these features, you may be able to run without it. But you are already have mongodb for the main data. Why don't you want to configure it ?

**Comment by lacrimal** [comment]
Really don't know why - maybe because it is no significant degradation of application functionality - we configured this.
We decided to not use thumbnail engine in early project phase.
Email attachments not bothered us at all from over a month now with 200 users.

Anyway - to enable it in current stage I need to configure smallfiles database connection and restart tomcat service ?
Will smallfiles database create itself automatically ?

**Comment by fmartin-linagora** [comment]
yes, it is very simple. reuse the same parameters as the other MongoDB connection (except the database name of course). 

For the database 'linshare-smallfiles' in MongoDB, it depends of your provider, you should follow the same procedure as the one you used to create 'linshare' database. 

Then you just have to restart, everything will work automatically, collections will be created in 'linshare-smalfiles' when needed. ;)
