### ISSUE TITLE
[Linshare 2.1.1] org.springframework.web.context.ContextLoader:initWebApplicationContext:Context initialization failed

### ISSUE THREAD

**Issue by fredo-m** [linagora/linshare#28]
I have updated a Linshare server from version 2.1.0 to 2.1.1.
After rebooting, Linshare does not work anymore. In the catalina.out log file there is the error message:

[ERROR]:localhost-startStop-1:20180530.151913:org.springframework.web.context.ContextLoader:initWebApplicationContext:Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'safeDetailService' defined in file [/var/lib/tomcat8/webapps/linshare/WEB-INF/classes/springContext-service.xml]: Bean instantiation via constructor 
failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.linagora.linshare.core.service.impl.SafeDetailServiceImpl]: Constructor threw exception; nested exception is java.lang.IllegalAr
gumentException: SafeDetail Invalid arguments
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:446)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:328)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.linagora.linshare.core.service.impl.SafeDetailServiceImpl]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: SafeDetail Invalid arguments
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
        ... 27 more
Caused by: java.lang.IllegalArgumentException: SafeDetail Invalid arguments
        at org.linagora.linshare.core.service.impl.SafeDetailServiceImpl.<init>(SafeDetailServiceImpl.java:73)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
        ... 29 more
30-May-2018 15:19:13.947 GRAVE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
30-May-2018 15:19:13.948 GRAVE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Erreur de démarrage du contexte [/linshare] suite aux erreurs précédentes

Regards.

**Comment by fmartin-linagora** [comment]
Hi,
Do you have some keys like safe.detail.* in your linshare.properties file ? If you do, please remove them abd try to restart Tomcat
Regards.

**Comment by fredo-m** [comment]
Hi,

Yes, I have the three lines "safe.detail.*" below:
safe.detail.country.code=FR
safe.detail.control.key=58
safe.detail.iufsc=test.iufsc

I commented on them and restarted tomcat, it works. Thank you.

Regards.
