### ISSUE TITLE
Mongo issue when starting tomcat

### ISSUE THREAD

**Issue by olsoncr** [linagora/linshare#45]
Hi, 

I have followed your documentation for linshare 2.2.1 in centos. I am able to see the user interfaces but the admin interfaces only shows the header and  an empty page.

This is the tomcat log:

v 19, 2018 12:21:08 AM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Nov 19, 2018 12:25:48 AM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Nov 19, 2018 12:25:48 AM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Nov 19, 2018 12:26:01 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'initMongoServiceImpl' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-mongo.xml]: Invocation of init method failed; nested exception is org.linagora.linshare.core.exception.BusinessException: User with uuid : root@localhost.localdomain not found.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1708)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:409)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.linagora.linshare.core.exception.BusinessException: User with uuid : root@localhost.localdomain not found.
	at org.linagora.linshare.core.service.impl.UserServiceImpl.findByLsUuid(UserServiceImpl.java:180)
	at org.linagora.linshare.core.service.impl.InitMongoServiceImpl.init(InitMongoServiceImpl.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1833)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1776)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1704)
	... 25 more

Nov 19, 2018 12:26:01 AM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext

**Comment by olsoncr** [comment]
and this is the catalina.log:

Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server version: Apache Tomcat/7.0.76
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server built: Oct 16 2018 09:15:49 UTC
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Server number: 7.0.76.0
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Name: Linux
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: OS Version: 3.10.0-862.14.4.el7.x86_64
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Architecture: amd64
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Java Home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Version: 1.8.0_191-b12
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: JVM Vendor: Oracle Corporation
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_BASE: /usr/share/tomcat
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: CATALINA_HOME: /usr/share/tomcat
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.awt.headless=true
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Xms512m
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Xmx2048m
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dlinshare.config.path=file:/etc/linshare/
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dlog4j.configuration=file:/etc/linshare/log4j.properties
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dspring.profiles.active=default,jcloud,mongo
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.base=/usr/share/tomcat
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Dcatalina.home=/usr/share/tomcat
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.endorsed.dirs=
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.io.tmpdir=/var/cache/tomcat/temp
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.config.file=/usr/share/tomcat/conf/logging.properties
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.VersionLoggerListener log
INFO: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
Nov 19, 2018 12:39:40 AM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFO: The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
Nov 19, 2018 12:39:40 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Nov 19, 2018 12:39:40 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["ajp-bio-8009"]
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 472 ms
Nov 19, 2018 12:39:40 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Nov 19, 2018 12:39:40 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.76
Nov 19, 2018 12:39:40 AM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat/webapps/linshare.war
Nov 19, 2018 12:39:47 AM org.apache.catalina.startup.TldConfig execute
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Nov 19, 2018 12:40:01 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Nov 19, 2018 12:40:01 AM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [/linshare] startup failed due to previous errors

**Comment by fmartin-linagora** [comment]
Hello,
Once you created the database, you must run the script createSchema.sql and import-postgresql.sql to inject default data. The user root@localhost.localdomain is part of the last script. Did you run both scripts ?

**Comment by fmartin-linagora** [comment]
Hi, there is no hard coded hostname. What is your problem ? debug traces would be appreciated.

**Comment by ilyesAj** [comment]
here is linshare.log
[linshare.log](https://github.com/linagora/linshare/files/5239543/linshare.log)

**Comment by fmartin-linagora** [comment]
It is weird, did you update the following parameter `linshare.db.hbm2ddl.auto=` in the linshare.properties file ?
It must be `linshare.db.hbm2ddl.auto=validate` otherwise Hibernate will try to drop/create the postgresql database schema. And we do not want this behaviour at all. You must run provided sql script to init postgresql database properly.
