### ISSUE TITLE
Trouble installing on Centos 7

### ISSUE THREAD

**Issue by ericdude101** [linagora/linshare#46]
Hello, Im trying to install LinShare 2.2.1 on CentOS 7 using the linshare-install-centos-7.md guide posted here on GitHub.

I was able to get through all the steps and all of the services are running, but I notice when I hit the URL the pages comes up all mal-formed, and the formatting appears to be broken. I'm also not sure if it's related but this message appears during the TomCat startup:

> Jan 05 14:22:02 linshare.local server[15413]: SEVERE: The web application [/linshare] appears to have started a thread named [com.google.inject.internal.util.$Finalizer] but has failed to stop it. This is very likely to create a memory leak.

It is also not creating the catalina log file at /var/tomcat/logs/catalina.out, but from what i've read this may be normal with the current version of CentOS & TomCat.

**Comment by yazidsebahi** [comment]
Hello,
Can you activate the log4j debug mode on log4j.properties to get the logs.
https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos-7.md#tomcat-7-configuration

**Comment by ericdude101** [comment]
I'm not seeing what I need to update to enable this?

**Comment by ericdude101** [comment]
I updated the last line in the file from log4j.category.org.linagora.linshare=info to log4j.category.org.linagora.linshare=DEBUG but either way it's not generating the log file. I did pull a dump from the most recent startup on the catalina.out file which appears to have a bunch of errors in it:

Jan 12 11:11:00 PRLS01 server: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-service.xml]: Cannot resolve reference to bean 'entryService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entryService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-service.xml]: Cannot resolve reference to bean 'documentEntryService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentEntryService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-service.xml]: Cannot resolve reference to bean 'documentEntryBusinessService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentEntryBusinessService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Cannot resolve reference to bean 'thumbnailGeneratorService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'thumbnailGeneratorService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: officeHome doesn't exist or is not a directory:
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
Jan 12 11:11:00 PRLS01 server: ... 40 more
Jan 12 11:11:00 PRLS01 server: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entryService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-service.xml]: Cannot resolve reference to bean 'documentEntryService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentEntryService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-service.xml]: Cannot resolve reference to bean 'documentEntryBusinessService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentEntryBusinessService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Cannot resolve reference to bean 'thumbnailGeneratorService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'thumbnailGeneratorService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: officeHome doesn't exist or is not a directory:
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
Jan 12 11:11:00 PRLS01 server: ... 52 more
Jan 12 11:11:00 PRLS01 server: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentEntryService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-service.xml]: Cannot resolve reference to bean 'documentEntryBusinessService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentEntryBusinessService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Cannot resolve reference to bean 'thumbnailGeneratorService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'thumbnailGeneratorService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: officeHome doesn't exist or is not a directory:
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
Jan 12 11:11:00 PRLS01 server: ... 64 more
Jan 12 11:11:00 PRLS01 server: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'documentEntryBusinessService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Cannot resolve reference to bean 'thumbnailGeneratorService' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'thumbnailGeneratorService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: officeHome doesn't exist or is not a directory:
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:140)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
Jan 12 11:11:00 PRLS01 server: ... 76 more
Jan 12 11:11:00 PRLS01 server: Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'thumbnailGeneratorService' defined in file [/var/lib/tomcat/webapps/linshare/WEB-INF/classes/springContext-business-service.xml]: Invocation of init method failed; nested exception is java.lang.IllegalStateException: officeHome doesn't exist or is not a directory:
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
Jan 12 11:11:00 PRLS01 server: at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
Jan 12 11:11:00 PRLS01 server: ... 88 more
Jan 12 11:11:00 PRLS01 server: Caused by: java.lang.IllegalStateException: officeHome doesn't exist or is not a directory:
Jan 12 11:11:00 PRLS01 server: at org.artofsolving.jodconverter.office.DefaultOfficeManagerConfiguration.buildOfficeManager(DefaultOfficeManagerConfiguration.java:160)
Jan 12 11:11:00 PRLS01 server: at org.linagora.LinThumbnail.ServiceOfficeManager.startOfficeManager(ServiceOfficeManager.java:77)
Jan 12 11:11:00 PRLS01 server: at org.linagora.LinThumbnail.impl.ThumbnailServiceImpl.start(ThumbnailServiceImpl.java:56)
Jan 12 11:11:00 PRLS01 server: at org.linagora.linshare.core.business.service.impl.ThumbnailGeneratorBusinessServiceImpl.start(ThumbnailGeneratorBusinessServiceImpl.java:137)

**Comment by yazidsebahi** [comment]
Can you show me your Linshare.propertties, please ?

**Comment by ericdude101** [comment]
Any chance there are any updates on this?

**Comment by yazidsebahi** [comment]
Can you send me the content of __/etc/sysconfig/tomcat__ and your __linshare.properties__ into downloadable file please

**Comment by ericdude101** [comment]
Yes:

https://drive.google.com/file/d/1snQtPUZ49NJ8Ib34cH0iNFGtVykNufhL/view?usp=sharing

**Comment by yazidsebahi** [comment]
ok, replace __log4j.rootCategory=INFO, CONSOLE__ by __log4j.rootCategory=INFO, LINSHARE__ in log4j.properties, and copy it into /etc/linshare  and restart please.

**Comment by ericdude101** [comment]
Alright, I made that change and rebooted the server.

**Comment by yazidsebahi** [comment]
ok, can you send me the content of /var/tomcat/logs/catalina.out please

**Comment by ericdude101** [comment]
I have included that log file along with the log4 properties file and a screenshot of the current behavior.

https://drive.google.com/file/d/1BeGQGyDGbrvKoRsH2cCa4oikm8osvZZ7/view?usp=sharing

**Comment by ericdude101** [comment]
Hello, I created a second virtual machine with a fresh installation of CentOS 7 and followed the same instructions but using version 2.0.1 as advertised on your main website just to test the potability of a version problem, but displays the same behavior.

**Comment by ericdude101** [comment]
Anybody out there that can shed some light? I'm sure its something silly like a config file or reverse proxy issue?

**Comment by ericdude101** [comment]
@yazidsebahi were you able to get anything from those logs or have any pointers? maybe someone else that can help?

**Comment by yazidsebahi** [comment]
hello @ericdude101, sorry for the delay we have been busy lately, your backend seems to start correctly without error, you can confirm that by using cURL to authenticate for example.
It works perfectly on Debian distribution, We will investigate more about CentOs.

**Comment by ericdude101** [comment]
Hello,

I made an effort to follow your recommendation and installed on Debian which yielded nearly the same result. The admin interface has color now when I launch it, but it shows like it's already logged in and nothing works.

What advice do you have for me now? I would really like to get this product working, but it's proving to be a difficult task unfortunately.

**Comment by ericdude101** [comment]
@yazidsebahi Any information or thoughts? - it's odd that i'm running into the exact same problem on ubuntu seeing as to how it's the preferred OS

**Comment by fmartin-linagora** [comment]
Hi,
can you send us your configuration files, version of linshare components, and logs from tomcat ?

**Comment by macinapp2** [comment]
Hello @ericdude101, I'm curious if you ever made additional progress on this issue. I am trying to setup linshare for the first time on a CetnOS 7. I also was not getting any output to catalina.out. I found this post: https://unix.stackexchange.com/questions/224380/tomcat-7-not-producing-log-output-to-catalina-out-on-rhel7
Which says:
> Creating a new file /etc/rsyslog.d/tomcat.conf containing the next two lines did the trick for me:
> 
> programname,contains,"server" /var/log/tomcat/catalina.out
> programname,contains,"server" ~
> Afterwards restart your rsyslog daemon:
> 
> service rsyslog restart

Now I'm seeing logs. I am able to load the webpage locally but the admin page comes up already logged in and mostly blank. Is this what you were seeing as well? 
I'm able to load the user page and it looks right but I'm not sure how to setup a username and password. I'm assuming that is done in the admin side. 
I'm attaching a screenshot of how the admin page looks. Hoping you made some progress that you can share. Thank you! 
![Screen Shot 2019-04-22 at 1 39 38 PM](https://user-images.githubusercontent.com/18740461/56515009-d63b5d00-6504-11e9-8ea2-fda86d283f51.png)

**Comment by ericdude101** [comment]
Hello @macinapp2, Your symptoms are almost identical to mine except for the fact that you have a colored frame on your interface. My broken site loaded up as just some hyperlinks and logout button on a completely white web page. Other than that yes, exactly the same.

I did stand up another VM running Ubuntu as requested by @yazidsebahi, and it didn't change anything other than it now loads up with a formatted and color frame identical to your screenshot - logged in and nothing there.

I was really hoping that by jumping over to Ubuntu would have been the cure since it's the supported operating system, however I was very disappointed when I went through the trouble just to obtain the exact same behavior

**Comment by macinapp2** [comment]
Ahh shoot. Sorry to hear you ran into the same problem on a different OS. Was really hoping to find a solution. I've been trying to get this working for over a week as a lot of this is new to me. Oh well, may switch to [Project Send](https://www.projectsend.org) if I don't find a solution soon. I don't have strong enough base knowledge to figure this one out on my own! At least I learned some new things. Good luck and thank you for the quick response.

**Comment by yazidsebahi** [comment]
Hello, 
The UI-admin start correctly but I think you have the backend (core) start with errors. 
Can you share with us the logs, please?

**Comment by macinapp2** [comment]
Hi,

I'm attaching my catalina.out log file. Please let me know uif you see anything in there that can help!

Thank you
[catalina.out.zip](https://github.com/linagora/linshare/files/3108436/catalina.out.zip)

**Comment by yazidsebahi** [comment]
You have database connection error, `org.postgresql.util.PSQLException: FATAL: password authentication failed for user "linshare"`, 
you need to check if the database started correctly, and check the login password on linshare.properties.

**Comment by macinapp2** [comment]
@yazidsebahi That did it! Thank you very much!

@ericdude101 Setting the postgreSQL password in the linshare.properties then restarting tomcat made the admin page function as expected! 

> [root@localhost ~]$ vi /etc/linshare/linshare.properties
> #******************** DATABASE
> ### PostgreSQL
> linshare.db.username=linshare
> linshare.db.password=**{PASSWORD}**
> linshare.db.driver.class=org.postgresql.Driver
> linshare.db.url=jdbc:postgresql://localhost:5432/linshare
> linshare.db.dialect=org.hibernate.dialect.PostgreSQLDialect

**Comment by ericdude101** [comment]
@macinapp2 Can you share what version of CentOS and Linshare components you are running?

**Comment by ericdude101** [comment]
@yazidsebahi I was able to make some progress and I not have a interface on CentOS similar to the one above, but i'm getting little tool tips in the left bar that say "The service is currently unavailable (HTTP code 503)."

Looking in the Apache logs for the admin interface, it shows:

> [Sat Apr 27 01:20:15.417555 2019] [proxy:error] [pid 15675] (13)Permission denied: AH00957: HTTP: attempt to connect to 127.0.0.1:8080 (127.0.0.1) failed
> [Sat Apr 27 01:20:15.417672 2019] [proxy:error] [pid 15675] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
> [Sat Apr 27 01:20:15.417716 2019] [proxy_http:error] [pid 15675] [client 10.1.0.35:50447] AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: http://linshare/
> [Sat Apr 27 01:20:15.484083 2019] [proxy:error] [pid 15675] AH00940: HTTP: disabled connection for (127.0.0.1)
> [Sat Apr 27 01:20:15.504519 2019] [proxy:error] [pid 15678] (13)Permission denied: AH00957: HTTP: attempt to connect to 127.0.0.1:8080 (127.0.0.1) failed
> [Sat Apr 27 01:20:15.504595 2019] [proxy:error] [pid 15678] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
> [Sat Apr 27 01:20:15.504627 2019] [proxy_http:error] [pid 15678] [client 10.1.0.35:50445] AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: http://linshare/
> [Sat Apr 27 01:22:15.889444 2019] [proxy:error] [pid 15675] (13)Permission denied: AH00957: HTTP: attempt to connect to 127.0.0.1:8080 (127.0.0.1) failed
> [Sat Apr 27 01:22:15.889501 2019] [proxy:error] [pid 15675] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
> [Sat Apr 27 01:22:15.889514 2019] [proxy_http:error] [pid 15675] [client 10.1.0.35:50458] AH01114: HTTP: failed to make connection to backend: 127.0.0.1, referer: http://linshare/

**Comment by yazidsebahi** [comment]
Hello, @ericdude101, 

I think this error is related to SELinux. 
Run the following command to allow apache to make outbound connections.

```/usr/sbin/setsebool -P httpd_can_network_connect 1```

**Comment by ericdude101** [comment]
@yazidsebahi doing that seems to have removed that message, now in the localhost_access_log im seeing :

> 127.0.0.1 - - [29/Apr/2019:05:42:02 -0700] "GET /linshare/webservice/rest/admin/authentication/authorized HTTP/1.1" 404 -
> 127.0.0.1 - - [29/Apr/2019:05:42:02 -0700] "GET /linshare/webservice/rest/admin/upgrade_tasks HTTP/1.1" 404 -
> 127.0.0.1 - - [29/Apr/2019:05:42:02 -0700] "GET /linshare/webservice/rest/admin/authentication/version HTTP/1.1" 404 -

**Comment by yazidsebahi** [comment]
@ericdude101 please try to execute this command to allow tomcat access to the DB. 
``` setsebool -P tomcat_can_network_connect_db 1 ```
keep us informed.

**Comment by g574** [comment]
Hi All,
I had this issue, and I managed to solve it.
Background: To integrate LinShare into my infrastructure, I had to change the Apache config files mentioned in the [guide](https://github.com/linagora/linshare/blob/master/documentation/EN/installation/linshare-install-centos.md#web-server-installation). I made a mistake, and it was redirecting to the wrong port.
My understanding is, that if we only see this non-complete page, it is what the files in `/var/www/linshare-ui-admin` contain, without the Tomcat application.
Why the application is not there, can have several reasons, e.g. it is not running because of wrong Postgresql credentials, as mentioned before. Or wrong redirection in my case.

To fix the logging issue, I also had to set `JAVA_HOME` and `CATALINA_BASE` in `/etc/sysconfig/tomcat`.
I hope it helps.
